/*
   qmk config options
   see https://github.com/qmk/qmk_firmware/blob/master/docs/config_options.md
 */
#define DEBOUNCE 5
#define LOCKING_SUPPORT_ENABLE
#define LOCKING_RESYNC_ENABLE
#define USB_POLLING_INTERVAL_MS 1
#define FORCE_NKRO

/* custom options */

#define ALTERNATE_VENDOR_ID 0x05Ac   // Apple
#define ALTERNATE_PRODUCT_ID 0x024f  // ANSI

#ifdef RADIAL_CONTROLLER_ENABLE
#  define RADIAL_CONTROLLER_EEPROM_ADDR VIA_EEPROM_CUSTOM_CONFIG_ADDR
#  define RADIAL_CONTROLLER_EEPROM_SIZE 4
#else
#  define RADIAL_CONTROLLER_EEPROM_SIZE 0
#endif
#define COMBO_COUNT 0
#define TAP_DANCE_ENTRIES 8
#define TAPPING_TERM_PER_KEY
#define DYNAMIC_TAP_DANCE_EEPROM_ADDR (VIA_EEPROM_CUSTOM_CONFIG_ADDR + RADIAL_CONTROLLER_EEPROM_SIZE)
#define DYNAMIC_TAP_DANCE_EEPROM_SIZE (TAP_DANCE_ENTRIES * 10)
#define VIA_EEPROM_CUSTOM_CONFIG_SIZE (RADIAL_CONTROLLER_EEPROM_SIZE + DYNAMIC_TAP_DANCE_EEPROM_SIZE)

#define CUSTOM_CONFIG_FORCE_RHID false
// can't enfore mac mode because it need to reset the keyboard
// #define CUSTOM_CONFIG_FORCE_MAC true
#define CUSTOM_CONFIG_FORCE_USJ false
