#pragma once

/* eeprom address */

#ifdef RADIAL_CONTROLLER_ENABLE
#  define RADIAL_CONTROLLER_EEPROM_ADDR VIA_EEPROM_CUSTOM_CONFIG_ADDR
#  define RADIAL_CONTROLLER_EEPROM_SIZE 4
#else
#  define RADIAL_CONTROLLER_EEPROM_SIZE 0
#endif
#define DYNAMIC_NON_MAC_FN_EEPROM_ADDR \
  (VIA_EEPROM_CUSTOM_CONFIG_ADDR + RADIAL_CONTROLLER_EEPROM_SIZE)
#define DYNAMIC_NON_MAC_FN_EEPROM_SIZE 56  // 27 keycodes + 2 bytes reserved
#define DYNAMIC_TAP_DANCE_EEPROM_ADDR \
  (DYNAMIC_NON_MAC_FN_EEPROM_ADDR + DYNAMIC_NON_MAC_FN_EEPROM_SIZE)
#define DYNAMIC_TAP_DANCE_EEPROM_SIZE (TAP_DANCE_ENTRIES * 10)
#define VIA_EEPROM_CUSTOM_CONFIG_COMMON_SIZE \
  (RADIAL_CONTROLLER_EEPROM_SIZE + DYNAMIC_NON_MAC_FN_EEPROM_SIZE + DYNAMIC_TAP_DANCE_EEPROM_SIZE)
#define VIA_EEPROM_CUSTOM_CONFIG_USER_ADDR \
  (VIA_EEPROM_CUSTOM_CONFIG_ADDR + VIA_EEPROM_CUSTOM_CONFIG_COMMON_SIZE)

/* maybe needed to re-define in each keyboard  */
#ifndef VIA_EEPROM_CUSTOM_CONFIG_SIZE
#  define VIA_EEPROM_CUSTOM_CONFIG_SIZE VIA_EEPROM_CUSTOM_CONFIG_COMMON_SIZE
#endif
