manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: petejohanson
      url-base: https://github.com/petejohanson
  projects:
    - name: zmk
      # remote: zmkfirmware
      # revision: main
      remote: petejohanson
      revision: core/zephyr-3.4-update
      import: app/west.yml
  self:
    path: zmk_keyboards
