#!/bin/zsh
#
# Usage:
#   DFU_HARDWARE_ID="<vid:pid>" make <kb>:<km>:flash DFU_PROGRAMMER=<path to this script>
#
# Requirements:
#    see https://learn.microsoft.com/en-us/windows/wsl/connect-usb
#    windows:
#      winget install dorssel.usbipd-win
#      winget install gerardog.gsudo
#    fedora:
#      sudo dnf install usbip hwdata
#
WIN_USBIPD="/mnt/c/Program Files/usbipd-win/usbipd.exe"
WIN_GSUDO="/mnt/c/Program Files/gsudo/Current/gsudo.exe"

# sudo for later use
sudo echo -n

dfu_device=$($WIN_USBIPD list 2> /dev/null | grep "$DFU_HARDWARE_ID")
if [[ -z $dfu_device ]]; then
  exit 1
fi

if [[ $dfu_device =~ "Shared" ]]; then
  win_usbipd_path=$(wslpath -w "$WIN_USBIPD")
  $WIN_GSUDO $win_usbipd_path attach --wsl --hardware-id $DFU_HARDWARE_ID
  exit 1
fi

if [[ $dfu_device =~ "Attached" ]]; then
  if lsusb | grep -q "$DFU_HARDWARE_ID"; then
    sudo chmod -R 777 /dev/bus/usb
    dfu-programmer "$@"
    exit 0
  fi
fi
exit 1
