#!/bin/zsh

WIN_USBIPD="/mnt/c/Program Files/usbipd-win/usbipd.exe"
WIN_USBIPD_PATH=$(wslpath -w "$WIN_USBIPD")
WIN_GSUDO="/mnt/c/Program Files/gsudo/Current/gsudo.exe"

# sudo for later use
sudo echo -n

dfu_device=$($WIN_USBIPD wsl list 2> /dev/null | grep "${DFU_USB_VID}:${DFU_USB_PID}")
if [[ -z $dfu_device ]]; then
  false
elif [[ $dfu_device =~ "Not attached" ]]; then
  $WIN_GSUDO $WIN_USBIPD_PATH wsl attach --hardware-id ${DFU_USB_VID}:${DFU_USB_PID}
  false
elif [[ $dfu_device =~ "Attached -" ]]; then
  if lsusb | grep -q "${DFU_USB_VID}:${DFU_USB_PID}"; then
    sudo chmod -R 777 /dev/bus/usb
    dfu-programmer $@
  else
    false
  fi
fi
