#define NUM_TAP_DANCE_PREDEFINED_ENTRIES 3

#define VIA_EEPROM_LAYOUT_OPTIONS_DEFAULT                                                    \
  (LAYOUT_OPTION_SPLIT_BS + LAYOUT_OPTION_SPLIT_RSHIFT_1_75U_1U + LAYOUT_OPTION_ENTER_ANSI + \
   LAYOUT_OPTION_BOTTOM_ROW_7U)
