# debounce
CONFIG_ZMK_KSCAN_DEBOUNCE_PRESS_MS=1
CONFIG_ZMK_KSCAN_DEBOUNCE_RELEASE_MS=3

CONFIG_BOOTSEL_STM32=y
CONFIG_BOOTSEL_STM32_ON_FATAL_ERROR=y

CONFIG_FLASH=y

CONFIG_SETTINGS_LOG_LEVEL_DBG=y

CONFIG_ZMK_RGB_UNDERGLOW_ON_START=n

# for debug / maintenance
CONFIG_FLASH_SHELL=y
CONFIG_SETTINGS_SHELL=y
